"""Generates the Clockblock adaptive-icon foreground + monochrome vector drawables.

"Two Clocks": a large marigold ring with a single hand (the clock you live by) and a smaller lavender ring with a
crescent (your body clock) sitting in front of it, up and to the right. The overlap is a real gap in the marigold
arc (not a knockout colour), so the monochrome themed-icon layer reads exactly the same in a single colour.

Only bold shapes (6-7.5 unit strokes on the 108 unit canvas), so the mark survives at 48 dp; the artwork is
centred on its bounding box and scaled so its farthest point sits at TARGET_EXTENT from the centre, inside the
66 dp (radius 33) adaptive-icon safe zone.

Usage: python3 tools/icon/gen_launcher_icon.py app/src/main/res/drawable
"""
import math
import sys

OUT = sys.argv[1] if len(sys.argv) > 1 else "."

# Authoring geometry (arbitrary origin; normalised below).
C1 = (0.0, 0.0)      # marigold clock centre
R1 = 18.5
W1 = 7.5
C2 = (14.5, -14.5)   # lavender body-clock centre
R2 = 11.0
W2 = 5.5
HALO = 2.6           # empty gap between the body-clock ring and the round ends of the marigold arc
HAND_ANGLE = -120    # degrees, y-down: 11 o'clock
HAND_LENGTH = 10.0
HAND_WIDTH = 6.0
HUB_RADIUS = 4.2     # the hand's pivot, so it reads as a clock hand rather than a dash
TARGET_EXTENT = 30.5  # farthest painted point from the canvas centre (safe zone radius is 33)

MARIGOLD = "#FFFFB000"
LAVENDER = "#FFC7C3FF"
MOON = "#FFF4F2FF"


def fmt(v):
    s = f"{v:.2f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def pt(c, r, a):
    return (c[0] + r * math.cos(a), c[1] + r * math.sin(a))


# --- Normalise: centre the bounding box on (54, 54) and scale to TARGET_EXTENT. ---------------------------
xmin = min(C1[0] - R1 - W1 / 2, C2[0] - R2 - W2 / 2)
xmax = max(C1[0] + R1 + W1 / 2, C2[0] + R2 + W2 / 2)
ymin = min(C1[1] - R1 - W1 / 2, C2[1] - R2 - W2 / 2)
ymax = max(C1[1] + R1 + W1 / 2, C2[1] + R2 + W2 / 2)
bc = ((xmin + xmax) / 2, (ymin + ymax) / 2)
raw_extent = max(math.dist(bc, C1) + R1 + W1 / 2, math.dist(bc, C2) + R2 + W2 / 2)
S = TARGET_EXTENT / raw_extent


def tp(p):
    return (54 + (p[0] - bc[0]) * S, 54 + (p[1] - bc[1]) * S)


c1, c2 = tp(C1), tp(C2)
r1, w1, r2, w2 = R1 * S, W1 * S, R2 * S, W2 * S


def circle(c, r):
    return f"M{fmt(c[0] - r)},{fmt(c[1])}a{fmt(r)},{fmt(r)} 0,1 1,{fmt(2 * r)},0a{fmt(r)},{fmt(r)} 0,1 1,{fmt(-2 * r)},0"


# Marigold arc: stops (round caps included) HALO short of the lavender ring.
reach = r2 + w2 / 2 + HALO * S + w1 / 2
d12 = math.dist(c1, c2)
toward = math.atan2(c2[1] - c1[1], c2[0] - c1[0])
half = math.acos((r1 * r1 + d12 * d12 - reach * reach) / (2 * r1 * d12))
a0, a1 = toward + half, toward - half + 2 * math.pi
p0, p1 = pt(c1, r1, a0), pt(c1, r1, a1)
marigold_arc = f"M{fmt(p0[0])},{fmt(p0[1])}A{fmt(r1)},{fmt(r1)} 0,1 1,{fmt(p1[0])},{fmt(p1[1])}"
lavender_ring = circle(c2, r2)

hand_tip = pt(c1, HAND_LENGTH * S, math.radians(HAND_ANGLE))
hand = f"M{fmt(c1[0])},{fmt(c1[1])}L{fmt(hand_tip[0])},{fmt(hand_tip[1])}"
hub = circle(c1, HUB_RADIUS * S / 2)

# Crescent: a disc minus a smaller disc offset towards the upper right (like Material's dark_mode glyph).
mr = 6.2 * S
mc = (c2[0] - 0.5 * S, c2[1] + 0.5 * S)
orr = 5.0 * S
oc = (mc[0] + 2.7 * S, mc[1] - 2.7 * S)
dx, dy = oc[0] - mc[0], oc[1] - mc[1]
d = math.hypot(dx, dy)
a = (d * d + mr * mr - orr * orr) / (2 * d)
h = math.sqrt(mr * mr - a * a)
px, py = mc[0] + a * dx / d, mc[1] + a * dy / d
i1 = (px - h * dy / d, py + h * dx / d)
i2 = (px + h * dy / d, py - h * dx / d)
moon = (
    f"M{fmt(i1[0])},{fmt(i1[1])}A{fmt(mr)},{fmt(mr)} 0,1 1,{fmt(i2[0])},{fmt(i2[1])}"
    f"A{fmt(orr)},{fmt(orr)} 0,0 0,{fmt(i1[0])},{fmt(i1[1])}Z"
)

print(f"scale {S:.3f}, marigold c={c1} r={r1:.2f}, lavender c={c2} r={r2:.2f}", file=sys.stderr)

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/icon/gen_launcher_icon.py: edit the script, not this file. -->
"""


def vector(comment, body):
    return (
        HEADER
        + f"<!-- {comment} -->\n"
        + """<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
"""
        + body
        + "</vector>\n"
    )


def stroke(name, d, color, w):
    return f"""    <path
        android:name="{name}"
        android:pathData="{d}"
        android:strokeWidth="{fmt(w)}"
        android:strokeColor="{color}"
        android:strokeLineCap="round" />
"""


def fill(name, d, color):
    return f"""    <path
        android:name="{name}"
        android:fillColor="{color}"
        android:pathData="{d}" />
"""


def body(m, l, moon_c):
    return (
        stroke("local_clock", marigold_arc, m, w1)
        + stroke("hand", hand, m, HAND_WIDTH * S)
        + stroke("hub", hub, m, HUB_RADIUS * S)
        + stroke("body_clock", lavender_ring, l, w2)
        + fill("moon", moon, moon_c)
    )


fg = vector(
    "Two Clocks: the marigold clock you live by (one hand) and, in front of it, the lavender body clock "
    "(a crescent). Bold shapes only, so it reads at 48dp; everything sits inside the 66dp safe zone.",
    body(MARIGOLD, LAVENDER, MOON),
)
mono = vector(
    "Themed-icon layer: the foreground's shapes in one colour (the gap in the arc keeps the two clocks apart).",
    body("#FFFFFFFF", "#FFFFFFFF", "#FFFFFFFF"),
)
with open(f"{OUT}/ic_launcher_foreground.xml", "w") as f:
    f.write(fg)
with open(f"{OUT}/ic_launcher_monochrome.xml", "w") as f:
    f.write(mono)
