package dev.sebastiano.clockblocker.opus.core.data.places

import dev.sebastiano.clockblocker.opus.core.model.Place
import java.io.BufferedReader

/**
 * Parser for `places.tsv` (generated by `tools/places/build_places.py`):
 * `code  name  city  country  zone  lat  lon  size  aliases(|-separated)`, `#` lines are comments.
 */
object PlaceTsv {
    const val AssetName: String = "places.tsv"
    private const val Columns = 9

    /** Thrown for a malformed row; the dataset is generated and tested, so this means a broken asset. */
    class MalformedRowException(lineNumber: Int, line: String, reason: String) :
        IllegalArgumentException("places.tsv line $lineNumber: $reason: '$line'")

    fun parse(reader: BufferedReader): List<PlaceRecord> {
        val out = ArrayList<PlaceRecord>(4500)
        var lineNumber = 0
        reader.forEachLine { line ->
            lineNumber++
            if (line.isNotBlank() && !line.startsWith('#')) out += parseLine(line, lineNumber)
        }
        return out
    }

    fun parse(text: String): List<PlaceRecord> = parse(text.reader().buffered())

    private fun parseLine(line: String, lineNumber: Int): PlaceRecord {
        val f = line.split('\t')
        if (f.size != Columns) throw MalformedRowException(lineNumber, line, "expected $Columns columns, got ${f.size}")
        val lat = f[5].toDoubleOrNull() ?: throw MalformedRowException(lineNumber, line, "bad latitude")
        val lon = f[6].toDoubleOrNull() ?: throw MalformedRowException(lineNumber, line, "bad longitude")
        val size = f[7].toIntOrNull() ?: throw MalformedRowException(lineNumber, line, "bad size")
        return PlaceRecord(
            place = Place(
                code = f[0],
                name = f[1],
                city = f[2],
                countryCode = f[3],
                zoneId = f[4],
                latitude = lat,
                longitude = lon,
            ),
            size = size,
            aliases = if (f[8].isEmpty()) emptyList() else f[8].split('|'),
        )
    }
}
